version: '3.9'

services:
  db:
    image: postgres:13.2
    container_name: enage-db
    environment:
      POSTGRES_DB: engage
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
  app:
    image: solution-app:latest
    build:
      context: .
    container_name: solution-app
    ports:
      - 8080:8080
    depends_on:
      - db
