# ==============================================================
# APP CONFIGURATION
# ==============================================================

app.solution.expense.vat-rate: 20.00

# ==============================================================
# ADAPTER CONFIGURATION
# ==============================================================

# Postgres
spring:
  datasource:
    url: jdbc:postgresql://${VRS_POSTGRES:localhost}/engage
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none

# Exchange
exchange-rate:
  api:
    primary:
      uri: https://api.exchangeratesapi.io
    secondary:
      uri: https://api.exchangerate.host

