# ==============================================================
# ADAPTER CONFIGURATION
# ==============================================================

# Postgres
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/engage
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none

# Exchange
exchange-rate:
  api:
    primary:
      uri: https://api.exchangeratesapi.io
    secondary:
      uri: https://api.exchangerate.host

